// Styles for OrderPromptModal, kept apart so the screen file holds behaviour only.
import { StyleSheet, Platform } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    justifyContent: "flex-end",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: Platform.OS === "ios" ? 40 : 24,
    maxHeight: "92%",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#EFECE6",
  },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  liveIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  badge: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 1,
  },
  title: {
    fontFamily: "serif",
    fontSize: 20,
    fontWeight: "700",
    color: colors.text,
  },
  closeBtn: {
    padding: 6,
    backgroundColor: "#F3F1EC",
    borderRadius: 20,
  },
  tabRow: {
    flexDirection: "row",
    backgroundColor: "#F4F1EA",
    borderRadius: 10,
    padding: 4,
    marginBottom: 14,
    gap: 4,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    borderRadius: 8,
  },
  tabBtnActive: {
    backgroundColor: colors.primary,
  },
  tabText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  tabTextActive: {
    color: "#FFFFFF",
  },
  tabContent: {
    marginBottom: 8,
  },
  summaryCard: {
    backgroundColor: "#F8F7F4",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#EAE6DE",
    padding: 14,
    marginBottom: 14,
  },
  summaryTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  customerName: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.text,
  },
  orderDate: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  orderTotal: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.primary,
  },
  statusRow: {
    flexDirection: "row",
    gap: 8,
  },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  statusPaid: {
    backgroundColor: "rgba(16, 185, 129, 0.15)",
  },
  statusPending: {
    backgroundColor: "rgba(245, 158, 11, 0.15)",
  },
  statusFulfilled: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
  },
  statusUnfulfilled: {
    backgroundColor: "rgba(239, 68, 68, 0.12)",
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 0.4,
  },
  label: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 6,
    marginTop: 4,
  },
  scopeRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  scopeBtn: {
    flex: 1,
    backgroundColor: "#F8F7F4",
    borderWidth: 1,
    borderColor: "#E5E1D8",
    borderRadius: 8,
    padding: 10,
    alignItems: "center",
  },
  scopeBtnActive: {
    backgroundColor: "rgba(122, 46, 60, 0.08)",
    borderColor: colors.primary,
    borderWidth: 1.5,
  },
  scopeLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textSecondary,
    marginBottom: 2,
  },
  scopeLabelActive: {
    color: colors.primary,
  },
  scopeAmount: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.text,
  },
  scopeAmountActive: {
    color: colors.primary,
  },
  telcoBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  telcoBadgeText: {
    fontSize: 10,
    fontWeight: "800",
  },
  input: {
    backgroundColor: "#F8F7F4",
    borderWidth: 1,
    borderColor: "#E5E1D8",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13,
    color: colors.text,
  },
  providerRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 12,
  },
  providerPill: {
    flex: 1,
    paddingVertical: 7,
    alignItems: "center",
    borderRadius: 6,
    backgroundColor: "#F3F1EC",
    borderWidth: 1,
    borderColor: "#E5E1D8",
  },
  providerPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  providerPillText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.text,
  },
  providerPillTextActive: {
    color: "#FFFFFF",
  },
  activePushCard: {
    backgroundColor: "#FAF7EE",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.gold,
    padding: 12,
    marginVertical: 10,
  },
  activePushHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  activePushTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 0.5,
  },
  activePushSub: {
    fontSize: 10,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  activePushText: {
    fontSize: 12,
    color: colors.text,
    lineHeight: 16,
    marginBottom: 8,
  },
  otpBox: {
    backgroundColor: "#FFFFFF",
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E1D8",
    marginTop: 6,
    marginBottom: 6,
  },
  checkStatusBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: colors.primary,
    marginTop: 6,
  },
  checkStatusText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.primary,
  },
  paidSuccessCard: {
    backgroundColor: "rgba(16, 185, 129, 0.08)",
    borderWidth: 1,
    borderColor: "#10B981",
    borderRadius: 14,
    padding: 24,
    alignItems: "center",
    marginVertical: 10,
  },
  paidSuccessTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#065F46",
    marginTop: 10,
    marginBottom: 6,
  },
  paidSuccessSub: {
    fontSize: 12,
    color: "#047857",
    textAlign: "center",
    lineHeight: 16,
  },
  phoneActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#EDE7D9",
  },
  phoneInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  phoneText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
  },
  quickContactBtns: {
    flexDirection: "row",
    gap: 6,
  },
  contactBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
  },
  contactBtnText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
  },
  templatesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 10,
  },
  templateChip: {
    backgroundColor: "#F3F1EC",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E1D8",
  },
  templateChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.text,
  },
  textArea: {
    height: 80,
  },
  charCount: {
    fontSize: 10,
    color: colors.textSecondary,
    marginTop: 2,
    textAlign: "right",
  },
  submitBtn: {
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    borderRadius: 10,
    marginTop: 14,
    marginBottom: 6,
  },
  submitBtnText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  cancelBtn: {
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
});
