// Styles for AccountScreen, kept apart so the screen file holds behaviour only.
import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  brandHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  brandTitle: {
    fontFamily: "serif",
    fontSize: 24,
    fontWeight: "700",
    color: colors.primary,
    letterSpacing: 3,
  },
  brandSubtitle: {
    fontSize: 9,
    fontWeight: "700",
    color: colors.textSecondary,
    letterSpacing: 2,
    marginTop: 2,
  },
  profileCard: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 20,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  avatarCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "800",
  },
  profileText: {
    marginLeft: 16,
    flex: 1,
  },
  userName: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 2,
  },
  userEmail: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  ownerRoleBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.primaryTint,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  ownerRoleText: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 0.5,
  },
  customerBadge: {
    backgroundColor: colors.successBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  customerBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.success,
  },
  backendLaunchBox: {
    backgroundColor: colors.primary,
    borderRadius: 20,
    padding: 22,
    alignItems: "center",
    marginBottom: 20,
  },
  launchIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  launchTitle: {
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 6,
  },
  launchSub: {
    fontSize: 12,
    color: "rgba(255,255,255,0.85)",
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 18,
  },
  openBackendBtn: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  openBackendText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  infoBox: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  infoBoxTitle: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  infoBoxValue: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.text,
  },
  sectionHeader: {
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 1,
  },
  emptyOrdersBox: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.borderLight,
    gap: 8,
  },
  emptyOrdersTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
  },
  emptyOrdersSub: {
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: "center",
  },
  ordersList: {
    gap: 10,
    marginBottom: 20,
  },
  orderCard: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  orderCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  orderNumber: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 0.5,
  },
  orderBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  badgePaid: {
    backgroundColor: colors.successBg,
  },
  badgePending: {
    backgroundColor: colors.warningBg,
  },
  orderBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.text,
  },
  orderDate: {
    fontSize: 10,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  orderCardBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
  },
  orderItemsCount: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  orderTotal: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.primary,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceWarm,
    borderRadius: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 8,
  },
  logoutText: {
    color: colors.error,
    fontSize: 12,
    fontWeight: "700",
  },
  authToggle: {
    flexDirection: "row",
    backgroundColor: colors.surfaceWarm,
    borderRadius: 20,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
  },
  toggleBtnActive: {
    backgroundColor: colors.primary,
  },
  toggleBtnText: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 0.8,
  },
  toggleBtnTextActive: {
    color: "#FFFFFF",
  },
  authCard: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  formTitle: {
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 4,
  },
  formSub: {
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 16,
    marginBottom: 16,
  },
  errorBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.errorBg,
    borderRadius: 10,
    padding: 10,
    marginBottom: 14,
    gap: 8,
  },
  errorBoxText: {
    color: colors.error,
    fontSize: 11,
    fontWeight: "600",
    flex: 1,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  input: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13,
    color: colors.text,
  },
  submitBtn: {
    backgroundColor: colors.primary,
    borderRadius: 20,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    marginBottom: 14,
  },
  submitBtnText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  phoneInputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
  },
  phoneInput: {
    flex: 1,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.text,
  },
  otpInput: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: 10,
    textAlign: "center",
    color: colors.text,
  },
  otpAutoNotice: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 6,
    textAlign: "center",
  },
  resendRow: {
    alignItems: "center",
    marginTop: 6,
    marginBottom: 8,
  },
  resendCooldownText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  resendBtnText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
  },
  ussdHintBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: colors.surfaceWarm,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginTop: 6,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  ussdHintText: {
    flex: 1,
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  backBtnRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 14,
  },
  backBtnText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "700",
  },
  staffLinkBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    marginTop: 4,
  },
  staffLinkText: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: "600",
  },
  staffModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  staffModalContent: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  staffModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  staffModalTitle: {
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  staffModalSub: {
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 16,
    marginBottom: 16,
  },
  infoBoxNotice: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.primaryTint,
    borderRadius: 10,
    padding: 10,
    marginBottom: 14,
    gap: 8,
  },
  infoBoxNoticeText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: "600",
    flex: 1,
  },
  updateCard: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: 16,
  },
  updateCardHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  updateIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F2EBE5",
    alignItems: "center",
    justifyContent: "center",
  },
  updateCardTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 1.2,
  },
  updateCardSubtitle: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  checkUpdateBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: "#FFFFFF",
  },
  checkUpdateBtnText: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 1,
  },
  updateResultBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  updateResultText: {
    fontSize: 11,
    color: colors.textSecondary,
    fontStyle: "italic",
    flex: 1,
  },
  updateDetailsBox: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  updateNotesTitle: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.text,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  updateNotesText: {
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 16,
    marginBottom: 10,
  },
  downloadUpdateBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
    paddingVertical: 10,
    borderRadius: 8,
  },
  downloadUpdateBtnText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },
  orderCardActionHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 8,
    gap: 4,
  },
  orderCardActionHintText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.primary,
  },
  orderModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  orderModalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
  },
  orderModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  orderModalNumber: {
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "700",
    color: colors.primary,
  },
  orderModalDate: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  orderModalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surfaceWarm,
    alignItems: "center",
    justifyContent: "center",
  },
  orderModalStatusRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  orderStatusPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceWarm,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  orderStatusPillLabel: {
    fontSize: 10,
    color: colors.textSecondary,
    fontWeight: "600",
  },
  orderStatusPillValue: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.text,
  },
  pillPaid: {
    backgroundColor: colors.successBg,
    borderColor: "rgba(39,110,64,0.2)",
  },
  pillPending: {
    backgroundColor: colors.warningBg,
    borderColor: "rgba(180,83,9,0.2)",
  },
  orderModalSectionTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 8,
  },
  orderItemsList: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
    gap: 10,
  },
  orderItemRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderItemName: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  orderItemVariant: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  orderItemPrice: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primary,
  },
  orderPricingCard: {
    backgroundColor: "#FAF9F6",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
    gap: 6,
  },
  orderPricingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  orderPricingLabel: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  orderPricingValue: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.text,
  },
  orderPricingTotalRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
    marginTop: 4,
  },
  orderPricingTotalLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.text,
  },
  orderPricingTotalValue: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.primary,
  },
  orderAddressBox: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  orderAddressName: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 2,
  },
  orderAddressLine: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 17,
  },
  orderAddressPhone: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    marginTop: 6,
  },
  receiptNoticeCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.successBg,
    borderRadius: 8,
    padding: 10,
    gap: 8,
    marginBottom: 14,
  },
  receiptNoticeCardText: {
    fontSize: 11,
    color: colors.success,
    fontWeight: "700",
    flex: 1,
  },
  orderModalActions: {
    marginTop: 14,
    gap: 10,
  },
  downloadReceiptBtn: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  downloadReceiptBtnText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  orderModalSubActions: {
    flexDirection: "row",
    gap: 10,
  },
  orderModalSubBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceWarm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 10,
  },
  orderModalSubBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  quickLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 20,
  },
  quickLinkText: { flex: 1, fontSize: 15, fontWeight: "600", color: colors.text },
  trackBtn: {
    marginLeft: "auto",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 3,
  },
  trackBtnText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800", letterSpacing: 1 },
});
