// Styles for OrdersScreen, kept apart so the screen file holds behaviour only.
import { StyleSheet, Platform } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.darkBg,
  },
  topHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "ios" ? 14 : 10,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.darkBorder,
  },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  liveIndicator: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: colors.gold,
  },
  portalBadge: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.gold,
    letterSpacing: 1.2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.darkText,
    fontFamily: "serif",
  },
  topHeaderBtns: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  iconBtn: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: colors.darkSurface,
    borderWidth: 1,
    borderColor: colors.darkBorder,
  },
  addOrderBtn: {
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  addOrderBtnText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.darkSurface,
    borderWidth: 1,
    borderColor: colors.darkBorder,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === "ios" ? 10 : 6,
  },
  searchInput: {
    flex: 1,
    color: colors.darkText,
    fontSize: 13,
  },
  filterScrollContainer: {
    marginBottom: 8,
  },
  filterScroll: {
    paddingHorizontal: 16,
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: colors.darkSurface,
    borderWidth: 1,
    borderColor: colors.darkBorder,
  },
  filterChipActive: {
    backgroundColor: colors.gold,
    borderColor: colors.gold,
  },
  filterChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.darkTextMuted,
  },
  filterChipTextActive: {
    color: "#182216",
    fontWeight: "800",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 90,
    gap: 12,
  },
  orderCard: {
    backgroundColor: colors.darkSurface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.darkBorder,
    padding: 14,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    paddingBottom: 8,
  },
  orderNumRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  orderNumber: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.gold,
  },
  preorderBadge: {
    backgroundColor: "rgba(245, 158, 11, 0.2)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  preorderBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#F59E0B",
  },
  orderDate: {
    fontSize: 11,
    color: colors.darkTextMuted,
    marginTop: 2,
  },
  badgesCol: {
    alignItems: "flex-end",
    gap: 4,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  statusBadgePaid: {
    backgroundColor: "rgba(16, 185, 129, 0.18)",
  },
  statusBadgePending: {
    backgroundColor: "rgba(245, 158, 11, 0.18)",
  },
  statusBadgeDelivered: {
    backgroundColor: "rgba(59, 130, 246, 0.18)",
  },
  statusBadgeProcessing: {
    backgroundColor: "rgba(168, 85, 247, 0.18)",
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "800",
  },
  statusBadgeTextPaid: {
    color: "#4ADE80",
  },
  statusBadgeTextPending: {
    color: "#FBBF24",
  },
  statusBadgeTextFulfill: {
    fontSize: 9,
    fontWeight: "700",
    color: "#93C5FD",
  },
  cardBody: {
    marginBottom: 12,
  },
  customerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  customerNameText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.darkText,
  },
  customerPhoneText: {
    fontSize: 12,
    color: colors.darkTextMuted,
  },
  itemsPreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  thumbsScroll: {
    flexDirection: "row",
  },
  thumbWrapper: {
    marginRight: 6,
  },
  thumbImg: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: "#2B3527",
  },
  thumbPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  itemCountText: {
    fontSize: 11,
    color: colors.darkTextMuted,
    fontWeight: "600",
  },
  destRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 4,
  },
  destText: {
    fontSize: 11,
    color: colors.darkTextMuted,
    flex: 1,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
    paddingTop: 8,
  },
  amountLabel: {
    fontSize: 10,
    color: colors.darkTextMuted,
  },
  amountValue: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.darkText,
  },
  depositNote: {
    fontSize: 10,
    color: colors.gold,
    fontWeight: "600",
  },
  actionButtonsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  momoPromptBtn: {
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
  },
  momoPromptBtnText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
  },
  receiptBtn: {
    backgroundColor: "rgba(202, 160, 86, 0.15)",
    borderWidth: 1,
    borderColor: colors.gold,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
  },
  receiptBtnText: {
    color: colors.gold,
    fontSize: 11,
    fontWeight: "800",
  },
  detailsBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  detailsBtnText: {
    fontSize: 11,
    color: "#C4B89D",
    fontWeight: "700",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 60,
  },
  loadingText: {
    color: colors.darkTextMuted,
    fontSize: 13,
    marginTop: 10,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80,
    paddingHorizontal: 30,
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.darkText,
    marginTop: 12,
  },
  emptySub: {
    fontSize: 12,
    color: colors.darkTextMuted,
    textAlign: "center",
    marginTop: 4,
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 20,
    paddingTop: 18,
    maxHeight: "92%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EFECE6",
  },
  modalOrderNumber: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.primary,
  },
  modalDate: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  closeBtn: {
    padding: 6,
    backgroundColor: "#F3F1EC",
    borderRadius: 20,
  },
  title: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.text,
  },
  detailSectionTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 1,
    marginTop: 12,
    marginBottom: 6,
  },
  detailCard: {
    backgroundColor: "#F8F7F4",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#EAE6DE",
    padding: 12,
    marginBottom: 6,
  },
  detailProductRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#EFECE6",
  },
  detailProdImg: {
    width: 44,
    height: 44,
    borderRadius: 6,
    backgroundColor: "#EAE6DE",
  },
  detailProdTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
  },
  detailProdVariant: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  detailProdPrice: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 2,
  },
  detailProdLineTotal: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.primary,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  infoLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: "600",
  },
  infoValue: {
    fontSize: 12,
    color: colors.text,
    fontWeight: "700",
    flexShrink: 1,
    textAlign: "right",
  },
  quickDialBtn: {
    backgroundColor: colors.primary,
    padding: 4,
    borderRadius: 4,
  },
  noteBox: {
    backgroundColor: "#FFFBEB",
    padding: 8,
    borderRadius: 6,
    marginTop: 6,
  },
  noteTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: "#B45309",
    marginBottom: 2,
  },
  noteText: {
    fontSize: 11,
    color: "#92400E",
  },
  breakdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  breakdownLabel: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  breakdownValue: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  grandBreakdownRow: {
    borderTopWidth: 1,
    borderTopColor: "#E5E1D8",
    paddingTop: 8,
    marginTop: 4,
  },
  grandBreakdownLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.primary,
  },
  grandBreakdownValue: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.primary,
  },
  depositAlert: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FAF7EE",
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.gold,
    marginTop: 8,
  },
  depositAlertText: {
    fontSize: 11,
    color: colors.text,
    fontWeight: "600",
    flex: 1,
  },
  modalActionButtons: {
    marginTop: 14,
    gap: 8,
  },
  primaryActionButton: {
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 10,
  },
  primaryActionText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  secondaryActionButton: {
    backgroundColor: "#F3F1EC",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E1D8",
  },
  secondaryActionText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "700",
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  optionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  optionPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: "#F3F1EC",
    borderWidth: 1,
    borderColor: "#E5E1D8",
  },
  optionPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  optionPillText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.text,
  },
  optionPillTextActive: {
    color: "#FFFFFF",
  },
  modalInput: {
    backgroundColor: "#F8F7F4",
    borderWidth: 1,
    borderColor: "#E5E1D8",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 13,
    color: colors.text,
    marginBottom: 10,
  },
});
