// Styles for StorefrontCartScreen, kept apart so the screen file holds behaviour only.
import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: colors.background,
  },
  iconBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  brandContainer: {
    alignItems: "center",
  },
  brandTitle: {
    fontFamily: "serif",
    fontSize: 22,
    fontWeight: "700",
    color: colors.primary,
    letterSpacing: 3,
  },
  brandSubtitle: {
    fontSize: 8,
    fontWeight: "700",
    color: colors.textSecondary,
    letterSpacing: 2,
    marginTop: 1,
  },
  cartIconWrapper: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  cartBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: colors.primary,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  cartBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "800",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  checkoutTitle: {
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 1.5,
    marginBottom: 18,
  },
  itemsList: {
    gap: 14,
    marginBottom: 20,
  },
  cartItemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  thumbnailContainer: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: "#E4E0D7",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  thumbnailImage: {
    width: "100%",
    height: "100%",
  },
  thumbnailFallback: {
    alignItems: "center",
    justifyContent: "center",
  },
  itemInfo: {
    flex: 1,
    marginLeft: 14,
  },
  itemTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  itemSubtitle: {
    fontSize: 10,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  itemPrice: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.primary,
  },
  controlsGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  quantityPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceWarm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  qtyBtn: {
    width: 22,
    height: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
  },
  qtyValueText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.text,
    paddingHorizontal: 8,
  },
  deleteBtn: {
    padding: 4,
  },
  freeShippingNotice: {

    backgroundColor: "#FBF5F6",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#EAD5D9",
    marginBottom: 8,
  },
  freeShippingNoticeActive: {
    backgroundColor: "#EDF7ED",
    borderColor: "#C8E6C9",
  },
  freeShippingNoticeText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.primary,
    flex: 1,
  },
  freeShippingNoticeTextActive: {
    color: "#2E7D32",
  },
  preorderDepositCard: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#EAD5D9",
    marginBottom: 10,
  },
  preorderDepositHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 3,
  },
  preorderDepositTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.primary,
    letterSpacing: 0.3,
  },
  preorderDepositSubtitle: {
    fontSize: 10,
    color: colors.textSecondary,
    marginBottom: 10,
  },
  preorderDepositTabs: {
    flexDirection: "row",
    gap: 8,
  },
  depositTab: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: "center",
    backgroundColor: colors.surface,
  },
  depositTabActive: {
    borderColor: colors.primary,
    backgroundColor: "#FBF5F6",
  },
  depositTabText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textSecondary,
    marginBottom: 2,
  },
  depositTabTextActive: {
    color: colors.primary,
    fontWeight: "700",
  },
  depositTabAmount: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.text,
  },
  summaryBox: {

    backgroundColor: colors.surfaceWarm,
    borderRadius: 16,
    padding: 16,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  summaryLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textSecondary,
    letterSpacing: 0.8,
  },
  summaryValue: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.text,
  },
  summaryTotalRow: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    marginTop: 8,
    paddingTop: 8,
  },
  totalLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: 1,
  },
  totalValue: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.primary,
  },
  sectionContainer: {
    marginTop: 14,
  },
  sectionHeaderLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 8,
  },
  deliveryTypeToggle: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
    marginBottom: 4,
  },
  deliveryTypeBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: colors.surfaceWarm,
    borderWidth: 1.5,
    borderColor: colors.borderLight,
  },
  deliveryTypeBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  deliveryTypeBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  deliveryTypeBtnTextActive: {
    color: "#FFFFFF",
  },
  cardSelectable: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 14,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cardContentLeft: {
    flex: 1,
    paddingRight: 10,
  },
  addressName: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 2,
  },
  addressDetail: {
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  paymentMethodText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 2,
  },
  paymentMethodSub: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  placeOrderBtn: {
    backgroundColor: colors.primary,
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    marginBottom: 12,
  },
  placeOrderText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  secureFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  secureText: {
    fontSize: 9,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 1,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 32,
  },
  emptyIconCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.surfaceWarm,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyTitle: {
    fontFamily: "serif",
    fontSize: 18,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: 18,
    marginBottom: 24,
  },
  browseBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
  },
  browseBtnText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontFamily: "serif",
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
  },
  modalSubtitleText: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textSecondary,
    marginBottom: 4,
    marginTop: 8,
  },
  input: {
    backgroundColor: colors.surfaceWarm,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 12,
    color: colors.text,
  },
  modalSaveBtn: {
    backgroundColor: colors.primary,
    borderRadius: 18,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 20,
  },
  modalSaveText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  paymentOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: colors.surfaceWarm,
    marginVertical: 6,
    gap: 12,
  },
  paymentOptionActive: {
    borderWidth: 1,
    borderColor: colors.primary,
  },
  paymentOptionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  paymentOptionSub: {
    fontSize: 10,
    color: colors.textSecondary,
    marginTop: 2,
  },
  testModeBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF3C7",
    borderColor: "#F59E0B",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 16,
  },
  testModeBannerTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#92400E",
    letterSpacing: 0.5,
  },
  testModeBannerSub: {
    fontSize: 10,
    color: "#B45309",
    marginTop: 2,
    lineHeight: 14,
  },
  momoCard: {
    backgroundColor: "#FDFBF7",
    borderColor: "#EAD5D9",
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  momoCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  momoCardTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 1,
  },
  momoCardSubtitle: {
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 16,
    marginBottom: 14,
  },
  momoInputLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textSecondary,
    marginBottom: 6,
    marginTop: 6,
    letterSpacing: 0.5,
  },
  networkSelectorRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  networkChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 8,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E1D8",
  },
  networkChipSelected: {
    borderColor: colors.primary,
    backgroundColor: "#FAF4F6",
    borderWidth: 1.5,
  },
  networkDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  networkChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.text,
  },
  networkChipTextSelected: {
    fontWeight: "800",
    color: colors.primary,
  },
  momoPhoneInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DCD6C9",
    overflow: "hidden",
    marginBottom: 10,
  },
  ghanaFlagPrefix: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: "#F5F2EB",
    borderRightWidth: 1,
    borderRightColor: "#E5E1D8",
  },
  momoPhoneInput: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
  },
  momoEmailInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DCD6C9",
    overflow: "hidden",
    marginBottom: 10,
  },
  momoEmailInput: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 13,
    color: colors.text,
  },
  momoSecurityNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F0EAE1",
  },
  momoSecurityNoticeText: {
    fontSize: 10,
    color: colors.textSecondary,
    flex: 1,
    lineHeight: 14,
  },
  momoModalHeaderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F7EFF1",
    alignItems: "center",
    justifyContent: "center",
  },
  momoPromptCard: {
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 16,
    backgroundColor: "#FAF7F3",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ECE6DC",
    marginBottom: 16,
  },
  momoPromptIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#F7EFF1",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  momoPromptEyebrow: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.primary,
    letterSpacing: 1.5,
    marginBottom: 4,
  },
  momoPromptAmount: {
    fontSize: 24,
    fontWeight: "800",
    color: colors.text,
    fontFamily: "serif",
    marginBottom: 8,
  },
  momoPromptRecipientBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#E5E1D8",
  },
  momoPromptRecipientText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  momoInstructionsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#EAE5DB",
    marginBottom: 14,
    gap: 10,
  },
  momoInstructionsTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.textSecondary,
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  instructionStepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  stepBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  stepBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
  },
  instructionStepText: {
    flex: 1,
    fontSize: 12,
    color: colors.text,
    lineHeight: 18,
  },
  momoErrorBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FEE2E2",
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  momoErrorText: {
    flex: 1,
    fontSize: 11,
    color: "#B91C1C",
    fontWeight: "600",
  },
  pollingNoticeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 8,
    marginBottom: 8,
  },
  pollingNoticeText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
  },
  modalActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    marginBottom: 14,
  },
  modalActionBtnText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1,
  },
  voucherSection: {
    backgroundColor: "#F9F8F5",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#ECE8E1",
    marginBottom: 12,
  },
  voucherSectionTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 2,
  },
  voucherSectionSub: {
    fontSize: 10,
    color: colors.textSecondary,
    lineHeight: 14,
    marginBottom: 8,
  },
  voucherInputRow: {
    flexDirection: "row",
    gap: 8,
  },
  voucherInput: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#DCD6C9",
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    color: colors.text,
  },
  voucherSubmitBtn: {
    backgroundColor: colors.text,
    borderRadius: 8,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  voucherSubmitBtnText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
  },
  simulateApprovalBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#FEF3C7",
    borderColor: "#F59E0B",
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    marginBottom: 10,
  },
  simulateApprovalBtnText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#92400E",
    letterSpacing: 0.5,
  },
});
