"use server";

import { revalidatePath } from "next/cache";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/auth";
import { recordAudit } from "@/lib/audit";
import { uniqueOrderNumber, logOrderEvent } from "@/lib/orders";
import { toMinorUnits, formatMoney } from "@/lib/money";
import type { PreorderRequestStatus } from "@/generated/prisma";

export async function updatePreorderRequestAction(formData: FormData): Promise<void> {
  const actor = await requirePermission("orders:write");

  const id = String(formData.get("id") ?? "");
  const status = String(formData.get("status") ?? "NEW") as PreorderRequestStatus;
  const targetBudgetRaw = String(formData.get("targetBudget") ?? "").trim();
  const staffNote = String(formData.get("staffNote") ?? "").trim();

  if (!id) return;

  let targetBudget: number | null = null;
  if (targetBudgetRaw) {
    const parsed = Number(targetBudgetRaw);
    if (Number.isFinite(parsed) && parsed >= 0) {
      targetBudget = toMinorUnits(parsed);
    }
  }

  await db.preorderRequest.update({
    where: { id },
    data: {
      status,
      targetBudget,
      staffNote: staffNote || null,
    },
  });

  await recordAudit({
    actorId: actor.id,
    action: "preorder_request.update",
    entity: "PreorderRequest",
    entityId: id,
    after: { status, targetBudget, staffNote },
  });

  revalidatePath("/admin/preorders");
}

export async function updateOrderPreorderMilestoneAction(formData: FormData): Promise<void> {
  const actor = await requirePermission("orders:write");
  const orderId = String(formData.get("orderId") ?? "");
  const preorderStage = String(formData.get("preorderStage") ?? "DEPOSIT_CONFIRMED");
  const preorderNote = String(formData.get("preorderNote") ?? "").trim();

  if (!orderId) return;

  await db.order.update({
    where: { id: orderId },
    data: {
      preorderStage,
      preorderNote: preorderNote || null,
    },
  });

  await logOrderEvent({
    orderId,
    type: "preorder.milestone_updated",
    message: `Pre-order milestone updated to ${preorderStage.replace(/_/g, " ")}${preorderNote ? `: ${preorderNote}` : ""}.`,
    actorId: actor.id,
  });

  revalidatePath("/admin/preorders");
  revalidatePath("/orders/track");
}

export async function convertPreorderRequestToQuoteOrderAction(
  formData: FormData,
): Promise<void> {
  const actor = await requirePermission("orders:write");
  const requestId = String(formData.get("requestId") ?? "");
  if (!requestId) return;

  const req = await db.preorderRequest.findUnique({ where: { id: requestId } });
  if (!req || req.convertedOrderId) return;

  const unitPrice = req.targetBudget ?? toMinorUnits(4500);
  const subtotal = unitPrice * req.quantity;
  const depositAmount = Math.round(subtotal * 0.5);
  const orderNumber = await uniqueOrderNumber();

  const nameParts = req.name.trim().split(/\s+/);
  const firstName = nameParts.shift() ?? req.name;
  const lastName = nameParts.join(" ") || "Client";

  const order = await db.order.create({
    data: {
      orderNumber,
      email: req.email,
      phone: req.phone,
      status: "PENDING",
      paymentStatus: "PENDING",
      hasPreorderItems: true,
      paymentMethod: "direct_momo",
      depositAmount,
      preorderStage: "DEPOSIT_CONFIRMED",
      preorderNote:
        req.staffNote ??
        "Bespoke sourcing quote generated by LaLuxury Concierge. 50% deposit reserves workshop production.",
      subtotal,
      total: subtotal,
      shippingAddress: {
        create: {
          firstName,
          lastName,
          phone: req.phone,
          line1: "White-Glove Concierge Delivery",
          city: "Accra",
          region: "Greater Accra",
          country: "GH",
        },
      },
      items: {
        create: [
          {
            productId: req.productId ?? null,
            productTitle: req.productTitle,
            variantTitle: req.variantTitle ?? "Bespoke Specification",
            sku: `BESPOKE-${orderNumber}`,
            imageUrl: req.imageUrl ?? null,
            isPreorder: true,
            preorderLeadTime: "4–6 weeks",
            quantity: req.quantity,
            unitPrice,
            total: subtotal,
          },
        ],
      },
    },
  });

  const reference = `${order.orderNumber}-QUOTE`;
  await db.payment.create({
    data: {
      orderId: order.id,
      reference,
      provider: "direct",
      channel: "bespoke_quote",
      amount: depositAmount,
      currency: "GHS",
      status: "PENDING",
    },
  });

  await db.preorderRequest.update({
    where: { id: req.id },
    data: {
      status: "QUOTED",
      convertedOrderId: order.orderNumber,
    },
  });

  await logOrderEvent({
    orderId: order.id,
    type: "preorder.quote_created",
    message: `Created bespoke quote order ${order.orderNumber} (${formatMoney(subtotal)}) from Custom Pre-Order Inquiry.`,
    actorId: actor.id,
  });

  revalidatePath("/admin/preorders");
  revalidatePath("/admin/orders");
}
